### ISSUE TITLE
请问这个项目进展如何

### ISSUE THREAD

**Issue by Oldpan** [GreatV/DocTrPP#2]
看到了这个doctr++项目的复现，很棒~
请问目前这个复现项目处于什么阶段呢，可以进行训练以及推理么？有提供预训练模型么？多谢~

**Comment by GreatV** [comment]
hi, @Oldpan , 我们正在进行整体网络结构对齐，预计还需要一段时间才能完成。后续会提供预训练模型。同时会集成到paddleocr仓库中，感谢你的关注，我们会尽快完成这项工作。

**Comment by Phbhan** [comment]
I trained this project and the result is not really well at this time. I just wonder have you trained and archived the same result as the paper? very appreciate your work.

**Comment by GreatV** [comment]
hi @Phbhan, This project is in progress.
