### ISSUE TITLE
你好，最近进展如何？

### ISSUE THREAD

**Issue by zhuxiaobin** [GreatV/DocTrPP#4]
你好，最近进展顺利么？我发现市面上很多扫描件基本都是歪的，在碰到复杂含图/表等页面的时候，只要市歪的，现有的版面分析有很大的失败概率，我自己写了个简答的算法，只能对歪的有效果，但是对于扫描时，页面发生弯曲的无解，我看论文似乎专门解决这个问题了。

**Comment by GreatV** [comment]
@zhuxiaobin  可能是前向没有对齐，现在效果不太行。等有时间，我再检查一下。

**Comment by zhuxiaobin** [comment]
好的，祝顺利！

**Comment by GreatV** [comment]
@zhuxiaobin 可以看下最新版本的效果
