### ISSUE TITLE
关于doc3D数据集问题

### ISSUE THREAD

**Issue by lizheng1992** [GreatV/DocTrPP#5]
能否借用一下账号密码下载一下数据集，万分感谢 azlizheng@gmail.com

**Comment by GreatV** [comment]
请参考这里的说明 https://github.com/cvlab-stonybrook/doc3D-dataset 
填写表单申请 https://forms.gle/RTfi7LUSrt891VuN8

**Comment by GreatV** [comment]
https://huggingface.co/datasets/StonyBrook-CVLab/doc3D-dataset
