### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by yitianlian** [GreatV/DocTrPP#6]
能否分享一下数据集，目前官方没发下载数据集

**Comment by GreatV** [comment]
请参考这里的说明 https://github.com/cvlab-stonybrook/doc3D-dataset
填写表单申请 https://forms.gle/RTfi7LUSrt891VuN8

**Comment by yitianlian** [comment]
我就是填了表单然后没有任何反馈

**Comment by yitianlian** [comment]
请问一下能否share一下QAQ？，我的email：xiechengxing34@gmail.com，非常感谢

**Comment by GreatV** [comment]
可以把下载脚本里的 http://vision.cs.stonybrook.edu/~sagnik/doc3d/img_1.zip 之类的链接提取出来替换成
https://bj.bcebos.com/paddleseg/paddleseg/datasets/doc3d/img_1.zip。后面的链接可以直接下载。

**Comment by zengchan** [comment]
我填了表单，给我发了密码，但是我下载的时候特别慢，只有几十K，请问怎么能解决？

**Comment by GreatV** [comment]
@zengchan 只能慢慢下，有时候很快，有时候比较慢。

**Comment by GreatV** [comment]
https://huggingface.co/datasets/StonyBrook-CVLab/doc3D-dataset
