### ISSUE TITLE
提供的模型实际效果怎么样

### ISSUE THREAD

**Issue by nissansz** [GreatV/DocTrPP#7]
提供的模型实际效果怎么样

**Comment by GreatV** [comment]
目前的效果 

![](https://raw.githubusercontent.com/GreatV/DocTrPP/main/doc/imgs/document_image_rectification.jpg)

**Comment by GreatV** [comment]
具体的你得自己试试

**Comment by nissansz** [comment]
模型下載不下來，明天再試試









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Wang Xin  ***@***.***>
 

 
 发送时间: 2024-04-26 23:09:33
 

 
 收件人:GreatV/DocTrPP ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Author ***@***.***> 

 
 主题: Re: [GreatV/DocTrPP] 提供的模型实际效果怎么样 (Issue #7)
 





 目前的效果
